services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - 3000:3000
    working_dir: /app/front
    volumes:
      - ./todo-react:/app/front

  todo-back:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:8080
    working_dir: /app/back
    volumes:
      - ./todo-backend:/app/back

  mongo-todo:
    image: mongo
    volumes:
      - todo-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bruce
      MONGO_INITDB_ROOT_PASSWORD: admin123

volumes:
  todo-mongo-data:
